---
- name: output cpu to file
  hosts: all
  become: yes

  tasks:
  - debug:
     var: ansible_processor_count

  - shell: df -h | grep /boot
    register: results

  - debug:
     var: results.stdout

  - debug:
       var: ansible_devices['dm-2'].size
