#====================циклы=================
---
- name: Loops Playbook
  hosts: all
  become: yes
  
  tasks:
  - name: Say Hello to all # писать всем 
    debug: msg="Hello {{ item }}"
    loop:  # ансимбл 2.5 и выше 
    with_items:  # ансимбл 2.4 и ниже 
        - "vasya":
    	- "kolya":
   	
  - name: loop until example
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output # вывести на экран 
	delay: 2 # задержка между запусками 2 секунды
	retries: 10 # по умолчанию 3 раза 
	until: output.stdout.find("ZZZZ") == false # делает пока не будет 4 z
	
  - name: Print final output
    debug:
	 var: output.stdout
	 
	
	
  -  	