
---
- name: Install default Apace Wev Server
  hosts: all
  become:yes
  
  
  tasks: 
  - name: Install Apace WebServer
    yum:  name=httpd state=latest
	
	
	-name: Start Apace and Enable it on the ever boot
	service: name=httpd state=started enabled=yes 